# Generated by Django 3.2.13 on 2022-11-22 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rates',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
