# Generated by Django 3.2.13 on 2022-11-21 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rate',
        ),
    ]
